FROM maven:3-openjdk-8-slim
RUN apt-get update -y && apt-get install -y unzip curl zip && \
		curl --silent --show-error --fail "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /opt/awscliv2.zip && \
			unzip /opt/awscliv2.zip && ls -ltra /opt/ && \ 
				./aws/install
RUN aws --version
WORKDIR /app
COPY . .
RUN mvn clean install -DskipTests
RUN chmod +x ./test-entrypoint.sh
CMD ["./test-entrypoint.sh"]